version: '3'

services:
  docs:
    image: made_by_carson_local_docs
    container_name: made_by_carson_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./made_by_carson:/app/made_by_carson:z
    ports:
      - '9000:9000'
    command: /start-docs
