name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Django Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: SSH key setup
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/made_by_carson
          docker compose -f /home/ubuntu/made_by_carson/production.yml down
          git pull origin master
          docker compose -f /home/ubuntu/made_by_carson/production.yml run --rm django python manage.py migrate
          docker compose -f /home/ubuntu/made_by_carson/production.yml up -d --build
          EOF
